---
- name: Zookeeper Installation
  include_tasks: 'tarball_install.yml'

- name: Enable zookeeper service
  service:
    name: '{{ zk_service_name }}'
    enabled: true
  become: true
  when:
    - zk_service_autostart

- name: Start service
  service:
    name: '{{ zk_service_name }}'
    state: started
  become: true
  when:
    - zk_service_start
