---
- hosts: master_nodes
  roles:
    - role: elasticsearch
  vars:
    es_instance_name: "node1"
    es_heap_size: "256m"
    es_config:
      cluster.name: "test-cluster"
      discovery.zen.ping.unicast.hosts: "elastic01:9300"
      http.port: 9200
      transport.tcp.port: 9300
      node.data: false
      node.master: true
      bootstrap.memory_lock: false
    es_scripts: false
    es_templates: false
    es_version_lock: false
    ansible_user: root

- hosts: data_nodes
  roles:
    - role: elasticsearch
  vars:
    es_instance_name: "node1"
    es_data_dirs: 
      - "/opt/elasticsearch"
    es_config:
      cluster.name: "test-cluster"
      discovery.zen.ping.unicast.hosts: "elastic02:9300"
      http.port: 9200
      transport.tcp.port: 9300
      node.data: true
      node.master: false
      bootstrap.memory_lock: false
    es_scripts: false
    es_templates: false
    es_version_lock: false
    ansible_user: root
    es_api_port: 9200
    
- hosts: data_nodes
  roles:
    - role: elasticsearch
  vars:
    es_instance_name: "node2"
    es_api_port: 9201
    es_config:
      discovery.zen.ping.unicast.hosts: "elastic02:9300"
      http.port: 9201
      transport.tcp.port: 9301
      node.data: true
      node.master: false
      bootstrap.memory_lock: false
      cluster.name: "test-cluster"
    es_scripts: false
    es_templates: false
    es_version_lock: false
    es_api_port: 9201
    ansible_user: root
